name: Add-Artifacts-to-Draft-Release

on:
  release:
    types:
      - created

jobs:
  add_artifacts:
    if: ${{ github.event.release.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: actions/setup-gh-cli@v2

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware-*
          path: ./artifacts

      - name: Upload Release Assets
        run: |
          for file in ./artifacts/*; do
            gh release upload "${{ github.event.release.tag_name }}" "$file" --clobber
          done
